esphome:
  name: daly-bat-1
  friendly_name: daly-bat-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "4lijFmifP0TDesopaSYiQSnVLmOr9HUGZ24p2JMxAzI="

ota:
  password: "22290a9715077b32fb1f4b57e43bd8a7"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  rx_buffer_size: 512

daly_bms:
  update_interval: 20s

sensor:
  - platform: daly_bms
    voltage:
      name: "Battery Voltage"
    current:
      name: "Battery Current"
    battery_level:
      name: "Battery Level"
    max_cell_voltage:
      name: "Max Cell Voltage"
      accuracy_decimals: 3
    max_cell_voltage_number:
      name: "Max Cell Voltage Number"
    min_cell_voltage:
      name: "Min Cell Voltage"
      accuracy_decimals: 3
    min_cell_voltage_number:
      name: "Min Cell Voltage Number"
    max_temperature:
      name: "Max Temperature"
    max_temperature_probe_number:
      name: "Max Temperature Probe Number"
    min_temperature:
      name: "Min Temperature"
    min_temperature_probe_number:
      name: "Min Temperature Probe Number"
    remaining_capacity:
      name: "Remaining Capacity"
    cells_number:
      name: "Cells Number"
    temperature_1:
      name: "Temperature 1"
    temperature_2:
      name: "Temperature 2"
    cell_1_voltage:
      name: "Cell 1 Voltage"
    cell_2_voltage:
      name: "Cell 2 Voltage"
    cell_3_voltage:
      name: "Cell 3 Voltage"
    cell_4_voltage:
      name: "Cell 4 Voltage"
    cell_5_voltage:
      name: "Cell 5 Voltage"     
    cell_6_voltage:
      name: "Cell 6 Voltage"  
    cell_7_voltage:
      name: "Cell 7 Voltage"  
    cell_8_voltage:
      name: "Cell 8 Voltage"  
    cell_9_voltage:
      name: "Cell 9 Voltage"  
    cell_10_voltage:
      name: "Cell 10 Voltage"  
    cell_11_voltage:
      name: "Cell 11 Voltage"  
    cell_12_voltage:
      name: "Cell 12 Voltage"  
    cell_13_voltage:
      name: "Cell 13 Voltage"  
    cell_14_voltage:
      name: "Cell 14 Voltage"  
    cell_15_voltage:
      name: "Cell 15 Voltage"  
    cell_16_voltage:
      name: "Cell 16 Voltage"   

text_sensor:
  - platform: daly_bms
    status:
      name: "BMS Status"


binary_sensor:
  - platform: daly_bms
    charging_mos_enabled:
      name: "Charging MOS"
    discharging_mos_enabled:
      name: "Discharging MOS"
